### ISSUE TITLE
Packages pages are completely broken

### ISSUE THREAD

**Issue by soredake** [omaha-consulting/winstall#170]
![изображение](https://github.com/omaha-consulting/winstall/assets/5204968/89398de9-3df4-4f96-8fc2-019cc78a83c4)

**Comment by jo-chemla** [comment]
Facing the same situation here

**Comment by Justin-Bento** [comment]
I used to have this with individual pages, however I get this error with pages using multiple packages

![image](https://github.com/user-attachments/assets/c081a0fc-c3f8-43ae-873c-b3709840b70e)

**Comment by soredake** [comment]
Fixed.
