### ISSUE TITLE
Winstall @ https://winstall.app/apps does not work at all

### ISSUE THREAD

**Issue by leowankerddd** [omaha-consulting/winstall#171]
I select a package and at the bottom of the screen it tells me that I need to select four more for a total of at least five before I can create a package. When I click on the button to create the pack it takes me to a website that wants me to log on to Twitter with an invalid link that goes nowhere.

If I select some apps and choose the button to generate the script it comes back and tells me that I have no app selected even though I have several.

Is there something that I'm doing wrong or does this service just not work anymore?
![2024-07-11_19-50-26](https://github.com/user-attachments/assets/ae6a5f7f-cd16-4dd9-b75e-a2a7d09dd8d2)
![2024-07-11_19-51-45](https://github.com/user-attachments/assets/12e22c20-0675-4a49-bfaa-16baa25d1e01)

**Comment by andersonbcn** [comment]
"It’s really not working. Even when you select a specific application to copy the command line individually, the page doesn't load and just loops without loading the content. It's been like this for a few days now. I've tried different browsers, but it behaves the same in all of them."

**Comment by mherrmann** [comment]
This is fixed, thank you.
