### ISSUE TITLE
Latest version/Version list incorrect/outdated for many packages

### ISSUE THREAD

**Issue by SlugFiller** [omaha-consulting/winstall#175]
Doing a random sampling of packages in https://github.com/microsoft/winget-pkgs updated in the past year vs information in https://winstall.app/, I found multiple that had an incorrect/outdated latest version listed on the site.

Here are a few examples:
https://github.com/microsoft/winget-pkgs/tree/master/manifests/b/Basedash/Basedash/1.16.0
Latest version on site - 1.15.0

https://github.com/microsoft/winget-pkgs/tree/master/manifests/g/GitExtensionsTeam/GitExtensions/4.2.1
Latest version on site - 4.1.0

https://github.com/microsoft/winget-pkgs/tree/master/manifests/g/GitHub/GitHubDesktop/3.4.5
Latest version on site - 3.4.3

https://github.com/microsoft/winget-pkgs/tree/master/manifests/h/HandBrake/HandBrake/1.8.2
Latest version on site - 1.8.1

https://github.com/microsoft/winget-pkgs/tree/master/manifests/j/JetBrains/ReSharper/2024.2.4
Latest version on site - 2024.2.3

https://github.com/microsoft/winget-pkgs/tree/master/manifests/w/Wasmer/Wasmer/4.3.7
Latest version on site - 4.3.6

https://github.com/microsoft/winget-pkgs/tree/master/manifests/y/Yandex/Browser/24.7.3.1136
Latest version on site - 24.7.2.1073

This also doesn't seem to be a simple time cutoff. While some of the above example are months old, below is an example of up-to-date version information that's only 2 weeks old:
https://github.com/microsoft/winget-pkgs/tree/master/manifests/j/JGraph/Draw/24.7.8

I could not figure out a clear rule as to what makes some packages out-of-date, and some up-to-date.

**Comment by mherrmann** [comment]
Thank you for reporting. This should be fixed.
